---

### global
letsencrypt_use_acme_live_directory: false
# set path of temporary directory for certificate creation
letsencrypt_temp_certficate_dir: "/var/tmp"
## set user and group of conf dirs to values of running user of the playbook
# overwrite in vars to allow usage of another user
letsencrypt_temp_cert_dir_user: "{{ lookup('env', 'USER') }}"
# overwrite in vars to allow usage of another group which may consist of more members
letsencrypt_temp_cert_dir_group: "{{ lookup('env', 'GROUP') }}"
# set packagemanager to use for localhost connections (yum, apt)
letsencrypt_prerequisites_packagemanager: "yum"
# region for s3 bucket when
letsencrypt_s3_config_region: "eu-west-1"

### http challenge / dns challenge
acme_directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
remaining_days: "30"
