- name: create the certificate for *.example.com
  hosts: localhost
  roles:
    - letsencrypt
  vars:
    domain:
      certificate_name: "wildcard.example.com"
      common_name: "*.example.com"
      zone: "example.com"
      email_address: "ssl-admin@example.com"
      subject_alt_name:
        - "example.com"
    letsencrypt_create_private_keys: true
    letsencrypt_do_http_challenge: false
    letsencrypt_do_dns_challenge: true
    letsencrypt_use_acme_live_directory: false
    account_email: "ssl-admin@example.com"
    private_key_content: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ....
    dns_user: "example_dns"
    dns_password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              ...
