---
- name: convert certificate to pfx format
  openssl_pkcs12:
    action: export
    path: "{{ pfx_cert_path }}"
    name: "{{ domain.certificate_name }}"
    privatekey_path: "{{ private_key_path }}"
    certificate_path: "{{ fullchain_path }}"
  when: convert_cert_to == "pfx"
