---
- name: Create RSA key to be used for acme account
  openssl_privatekey:
    path: "{{ account_key_path }}"
    size: 4096
    type: RSA
  no_log: true

- name: Create RSA key to be used for certificate
  openssl_privatekey:
    path: "{{ private_key_path }}"
  when:
    - private_key_content is not defined

- name: create private key file from private_key_content-variable
  copy:
    dest: "{{ private_key_path }}"
    content: "{{ private_key_content }}"
    mode: 0400
  when:
    - private_key_content is defined
