---
- name: Create CSR for certificate
  openssl_csr:
    path: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}.csr"
    privatekey_path: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}.key"
    email_address: "{{ domain.email_address }}"
    common_name: "{{ domain.common_name }}"
    subject_alt_name: "DNS:{{ domain.subject_alt_name | join(',DNS:') }}"

- name: Create a challenge for {{ domain.common_name }} using a account key file.
  acme_certificate:
    account_key_src: "{{ temp_certficate_dir.path }}/letsencrypt_account.pem"
    account_email: "{{ account_email }}"
    csr: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}.csr"
    cert: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}.pem"
    challenge: dns-01
    force: "{{ force_renewal | default(false) }}"
    acme_directory: "{{ acme_directory }}"
    acme_version: 2
    terms_agreed: true
    remaining_days: "{{ remaining_days }}"
  register: challenge

### include/role 3 - validate challenge
- name: validate challenge only if it is created or changed
  when: challenge is changed
  block:
    - name: Login to autodns
      uri:
        url: "https://api.autodns.com/v1/login"
        method: POST
        body_format: json
        body:
          { "context": "4",
            "user": "{{ dns_user }}",
            "password": "{{ dns_password }}"
          }
      register: login
      no_log: true

    - name: add a new TXT record to the common domain
      uri:
        url: "https://api.autodns.com/v1/zone/{{ domain.zone }}/a.ns14.net"
        method: PATCH
        body_format: json
        body:
          {
            "origin": "{{ domain.zone }}",
            "resourceRecordsAdd": [
              {
                "name": "_acme-challenge",
                "ttl": 60,
                "type": "TXT",
                "value": "{{ challenge['challenge_data'][domain.common_name]['dns-01']['resource_value'] }}"
              }
            ]
          }
        headers:
          Cookie: "{{ login.set_cookie }}"
      when:
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][domain.common_name] is defined

    - name: add a new TXT record to the SAN domains
      uri:
        url: "https://api.autodns.com/v1/zone/{{ domain.zone }}/a.ns14.net"
        method: PATCH
        body_format: json
        body:
          {
            "origin": "{{ item }}",
            "resourceRecordsAdd": [
              {
                "name": "_acme-challenge.{{ item }}",
                "ttl": 60,
                "type": "TXT",
                "value": "{{ challenge['challenge_data'][item]['dns-01']['resource_value'] }}"
              }
            ]
          }
        headers:
          Cookie: "{{ login.set_cookie }}"
      loop: "{{ domain.subject_alt_name }}"
      when:
        - domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined

    - name: Let the challenge be validated and retrieve the cert and intermediate certificate
      acme_certificate:
        account_key_src: "{{ temp_certficate_dir.path }}/letsencrypt_account.pem"
        account_email: "{{ account_email }}"
        csr: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}.csr"
        cert: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}.pem"
        fullchain: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}_fullchain.pem"
        chain: "{{ temp_certficate_dir.path }}/{{ domain.certificate_name }}_intermediate.pem"
        challenge: dns-01
        force: "{{ force_renewal | default(false) }}"
        acme_directory: "{{ acme_directory }}"
        acme_version: 2
        terms_agreed: true
        remaining_days: "{{ remaining_days }}"
        data: "{{ challenge }}"

    - name: remove created TXT record to keep DNS zone clean
      uri:
        url: "https://api.autodns.com/v1/zone/{{ domain.zone }}/a.ns14.net"
        method: PATCH
        body_format: json
        body:
          {
            "origin": "{{ domain.zone }}",
            "resourceRecordsRem": [
              {
                "name": "_acme-challenge",
                "ttl": 60,
                "type": "TXT",
                "value": "{{ challenge['challenge_data'][domain.common_name]['dns-01']['resource_value'] }}"
              }
            ]
          }
        headers:
          Cookie: "{{ login.set_cookie }}"
      when:
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][domain.common_name] is defined

    - name: remove created SAN TXT records to keep DNS zone clean
      uri:
        url: "https://api.autodns.com/v1/zone/{{ domain.zone }}/a.ns14.net"
        method: PATCH
        body_format: json
        body:
          {
            "origin": "{{ item }}",
            "resourceRecordsRem": [
              {
                "name": "_acme-challenge.{{ item }}",
                "ttl": 60,
                "type": "TXT",
                "value": "{{ challenge['challenge_data'][item]['dns-01']['resource_value'] }}"
              }
            ]
          }
        headers:
          Cookie: "{{ login.set_cookie }}"
      loop: "{{ domain.subject_alt_name }}"
      when:
        - domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined
