- name: set fact for acme_directory
  set_fact: acme_directory="{{ acme_live_directory }}"
  when:
    - letsencrypt_use_acme_live_directory | bool

- name: create directories for letsencrypt
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ letsencrypt_conf_dir }}"
    - "{{ letsencrypt_cert_dir }}"
